<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

In [2]:
import numpy as np
import time
import sys

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [73]:
def sma(a:np.ndarray,n:int)->list:
    
    """
    sma(a,n)

    Calcula medias moviles simples de todos los grupos de n numeros susecivos con saltos de 1 en cada grupo.

    Parameters
    ----------
    a : np.array
        lista de numeros
    n : int
        Numero de terminos.

    Returns
    -------
    output : np.array
        Medias moviles simples sucesivas.
        
    Examples
    --------
    >>> sma([5,3,8,10,2,1,5,1,0,2], 2) =  [4.,5.5,9.,6.,1.5,3.,3.,0.5,1.]
    """
    b=np.cumsum(a)
    l=np.linspace(0,0,np.size(a)-n+1) 
    l[0]=float(b[n-1]/n)#El primer termino es delicado.
    for i in range (0,np.size(a)-n): #Agregamos los siguiendes siguiendo la regla de los pasos indicada
        d=float((b[n+i]-b[i])/n)
        l[i+1]=d
    return(l)    
        
    
    

In [74]:
sma([5,3,8,10,2,1,5,1,0,2], 2) 


array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [100]:
def strides(a: np.ndarray,n:int,p:int)->np.ndarray:
    
    """
    strides(a,n,p)

    Transforma un arreglo unidimensional  𝑎  en una matriz de  𝑛  columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en  𝑝  pasos

    Parameters
    ----------
    a : n.array
        Arreglo a transformar
        
    n : int
        Numero de columnas del matriz resultante.
    p : int
        Numero de pasos

    Returns
    -------
    output : no.array
        Matriz de n columnas cuyas filas son posiciones consecutivas y desfasadas en p pasos del arreglo a.
        
    """
    A=np.zeros([np.size(a)-(n+p),n]) #Definimos las cantidad de filas y columnas de la matriz como una que solo contiene 0´s
    for i in range (0,np.size(a)-(n+p)): #Iteramos sobre las columnas
        for j in range(0,n):c #iteramos sobre las columnas para acceder a todos los elementosde la matriz
            A[i,j]=a[j+p*i] #Asignamos el elemento del array a correpondiente a los pasos
    
    
    return(A)   

In [101]:
#EJEMPLO
a=np.array([1,2,3,4,5,6,7,8,9,10])
strides(a,4,2)


array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [36]:
def Validar_Matriz(A: np.ndarray)->bool: #Funcion que va a validar si la Matriz es cuadrada y si conttiene los numeros del 1 al n^2
    if A.shape[0] != A.shape[1]: #chekeamos si es cuadrada
        return False
    n=A.shape[1]
    a=np.ravel(A) #Transformamaos la matriz en una array plano para trabajar mas comodos
    for i in range (1 , n**2+1): #Chekeamos que esten los numeros del 1 al n^2
        if i not in a:
            return False
    return True

In [40]:
B=np.array([[4,2,9],[3,5,7],[8,1,6]])
Validar_Matriz(B)

False

In [43]:
def es_cuadrado_magico(A: np.ndarray)->bool:
    
    """
    es_cuadrado_magico(A)

    Valid si la matris A es un cuadrado magico

    Parameters
    ----------
    A : n.array
        Matriz a validar
        
    Returns
    -------
    output : Bool
        Verdadero si la matriz es un cuadrado magico , False en caso contrario.
        
    """
    
    if Validar_Matriz(A)==True:
        n=A.shape[1]
        a=A.ravel
        for i in range (0,n): #Validamos las sumas de las filas
            if np.sum(A[:,i]) == (n*(n**2+1))/2:
                pass
            else:
                return(False)
        for i in range (0,n):
            if np.sum(A[i,:]) == (n*(n**2+1))/2:#Validamos las sumas de las columnas
                pass
            else:
                return(False)
        if np.sum(np.diag(A)) == (n*(n**2+1))/2: #Validamos diagonal principal
            pass
        else:
            return(False)
        if np.sum(np.diag(np.fliplr(A))) == (n*(n**2+1))/2: #Validamos diagonal secundaria
            pass
        else:
            return(False)
        return(True)#Validamos que sea cuadrada
    
    else:
        return False

In [31]:
A=np.array([[4,9,2],[3,5,7],[8,1,6]])
es_cuadrado_magico(A)
A

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [45]:
B=np.array([[4,2,9],[3,5,7],[8,1,6]])
es_cuadrado_magico(B)

False